language: go

dist: xenial

go:
- 1.12.x

notifications:
  email: false

env:
  global:
    - GO111MODULE=on

before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv -in .env.enc -out .env -d || true'
- nvm install 12
- npm install -g npm@6.x
- sudo apt-get update
- sudo apt-get install python

install:
- curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0

script:
# This step is required since we use a go module
- go mod download
- golangci-lint run
- curl https://us-south.functions.appdomain.cloud/api/v1/web/e6b54af6-ab44-4149-a8e4-e906dcc58136/default/secadvstg-location-shift.json
- go test ./...
- go test `go list ./...` -tags integration

before_deploy:
- pip install --user bumpversion
- npm install @semantic-release/changelog
- npm install @semantic-release/exec
- npm install @semantic-release/git
- npm install @semantic-release/github

deploy:
- provider: script
  on:
    branch: main
  skip_cleanup: true
  script: npx semantic-release --repository-url https://${GH_TOKEN}@github.com/ibm-cloud-security/scc-go-sdk --debug